import React from "react";
import {
  Box,
  Card,
  CardContent,
  Typography
} from "@material-ui/core";

export default function Intro() {

  return (
    <Card className="home-centered" elevation={0} >
      <Box className="home-colorBackground">
        <CardContent>
          <Typography className="home-intro-title">
            BioCompute: A platform for bioinformatics analysis workflow documentation
          </Typography>
          <Typography>
            BioCompute is shorthand for the IEEE 2791-2020 standard for Bioinformatics Analyses Generated by High-Throughput Sequencing (HTS) to facilitate communication. This pipeline documentation approach has been adopted by a few FDA centers. The goal is to ease the communication burdens between research centers, organizations, and industries. This web portal allows users to build a BioCompute Objects through the interface in a human and machine readable format.
          </Typography>
          
        </CardContent>
      </Box>
    </Card>
  );
}
