import React from "react";
import {
    Box,
  Card,
  CardActionArea,
  CardContent,
  makeStyles,
  Paper,
  Typography
} from "@material-ui/core";
import { Link } from "react-router-dom";
import Background from "../../images/background.jpg"

const useStyles = makeStyles({
  bullet: {
    display: "inline-block",
    margin: "0 2px",
    transform: "scale(0.8)",
  },
  centered: {
    minWidth: 275,
    textAlign: "center",
    marginTop: 0
  },
  heightened: {
    minHeight: "250px"
  },
  title: {
    fontSize: "33px",
  },
  pos: {
    marginBottom: 12,
  },
  colorBackground: {
    backgroundColor: "#D8EDF9"
  }
});

export default function Intro(props) {
  const classes = useStyles();

  return (
    <Card className={classes.centered} elevation={0} >
        <Box className={classes.colorBackground}>
        <CardContent className={classes.linkCard} >
        
            <Typography className={classes.title}>
            BioCompute: A platform for bioinformatics analysis workflow documentation
          </Typography>
          <Typography>
            BioCompute is shorthand for the IEEE 2791-2020 standard for Bioinformatics Analyses Generated by High-Throughput Sequencing (HTS) to facilitate communication. This pipeline documentation approach has been adopted by a few FDA centers. The goal is to ease the communication burdens between research centers, organizations, and industries. This web portal allows users to build a BioCompute Objects through the interface in a human and machine readable format.
          </Typography>
          
        </CardContent>
      </Box>
    </Card>
  );
}
