// src/views/home/HomeView/Specification.js

import React from "react";
import {
  Card,
  CardActionArea,
  CardContent,
  makeStyles,
  Typography
} from "@material-ui/core";
import ieee from "../../images/ieee.jpg";

const useStyles = makeStyles({
  bullet: {
    display: "inline-block",
    margin: "0 2px",
    transform: "scale(0.8)",
  },
  linkCard: {
    minHeight: "300px",
    minWidth: 275,
    textAlign: "center",
    marginBottom: 12
  },
  title: {
    fontSize: "33px",
  },
  pos: {
    marginBottom: 12,
  },
});

export default function Specification() {
  const classes = useStyles();
  const ieeeLink = "https://standards.ieee.org/standard/2791-2020.html";

  return (
    <Card className={classes.linkCard} elevation={1}>
      <CardActionArea onClick={() => window.open(ieeeLink)}>
        <CardContent className={classes.linkCard}>
          <Typography className={classes.title}>
            IEEE 2791-2020
          </Typography>
          <Typography className={classes.bullet}>
            IEEE Standard for Bioinformatics Analyses
            Generated by High-Throughput Sequencing (HTS) to Facilitate Communication
            <br />
            <br />
            <img src={ieee} width={150} alt="IEEE logo" />
          </Typography>
        </CardContent>
      </CardActionArea>
    </Card>
  );
}
