// src/views/home/HomeView/Specification.js

import React from "react";
import {
  Card,
  CardActionArea,
  CardContent,
  Typography
} from "@material-ui/core";
import ieee from "../../images/ieee.jpg";

export default function Specification() {
  const ieeeLink = "https://standards.ieee.org/standard/2791-2020.html";

  return (
    <Card className="home-linkcard" elevation={1}>
      <CardActionArea onClick={() => window.open(ieeeLink)}>
        <CardContent className="home-linkcard">
          <Typography className="home-intro-title">
            IEEE 2791-2020
          </Typography>
          <Typography className="home-bullet">
            <img src={ieee} width={150} alt="IEEE logo" />
            <br />
            <br />
            IEEE Standard for Bioinformatics Analyses
            Generated by High-Throughput Sequencing (HTS) to Facilitate Communication
            <br />
            <br />
            <img src={ieee} width={150} alt="IEEE logo" />
          </Typography>
        </CardContent>
      </CardActionArea>
    </Card>
  );
}
