# Generated by Django 4.1.5 on 2023-01-03 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BcoDb',
            fields=[
                ('hostname', models.CharField(max_length=255)),
                ('human_readable_hostname', models.CharField(max_length=255)),
                ('public_hostname', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('user_permissions', models.JSONField()),
                ('group_permissions', models.JSONField()),
                ('account_creation', models.DateTimeField()),
                ('account_expiration', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('recent_status', models.CharField(max_length=255)),
                ('recent_attempt', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
