# Generated by Django 4.1.5 on 2023-01-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bcodb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bcodb",
            name="account_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
