# Generated by Django 4.1.5 on 2023-01-03 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('bcodb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcodb',
            name='username',
        ),
        migrations.AddField(
            model_name='bcodb',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
