# Generated by Django 4.1.5 on 2023-01-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bcodb", "0002_bcodb_account_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bcodb",
            name="account_expiration",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bcodb",
            name="created",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
