# Generated by Django 4.1.5 on 2023-01-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcodb', '0002_remove_bcodb_username_bcodb_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcodb',
            name='account_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bcodb',
            name='account_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bcodb',
            name='group_permissions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bcodb',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bcodb',
            name='user_permissions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
