# Generated by Django 4.1.5 on 2023-01-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcodb', '0004_alter_bcodb_group_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcodb',
            name='user_permissions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
