# Generated by Django 4.1.5 on 2024-05-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bcodb", "0007_bco"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bcodb",
            name="group_permissions",
        ),
    ]
