# Generated by Django 4.1.5 on 2023-01-16 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prefix",
            fields=[
                (
                    "prefix",
                    models.CharField(
                        max_length=5, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("registration_date", models.DateTimeField()),
                ("registration_certificate", models.CharField(max_length=1000)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
    ]
