name: UserDb Django CI

on:
  push:
    branches: [main, 23.12]
  pull_request:
    branches: [main, 23.12]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: 'server'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
      - name: Run Tests
        run: |
          cd server/
          python3.9 manage.py test
